# Generated by Django 4.0.5 on 2022-06-25 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_author_inventory_suuplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='suuplier',
            new_name='supplier',
        ),
    ]
